// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: broadcast_event.proto

package protoc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//游戏中的广播事件
type BroadcastEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	// Types that are assignable to Event:
	//	*BroadcastEvent_ReadyEvent
	//	*BroadcastEvent_StartGameEvent
	Event isBroadcastEvent_Event `protobuf_oneof:"Event"`
}

func (x *BroadcastEvent) Reset() {
	*x = BroadcastEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastEvent) ProtoMessage() {}

func (x *BroadcastEvent) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastEvent.ProtoReflect.Descriptor instead.
func (*BroadcastEvent) Descriptor() ([]byte, []int) {
	return file_broadcast_event_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (m *BroadcastEvent) GetEvent() isBroadcastEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *BroadcastEvent) GetReadyEvent() *ReadyEvent {
	if x, ok := x.GetEvent().(*BroadcastEvent_ReadyEvent); ok {
		return x.ReadyEvent
	}
	return nil
}

func (x *BroadcastEvent) GetStartGameEvent() *StartGameEvent {
	if x, ok := x.GetEvent().(*BroadcastEvent_StartGameEvent); ok {
		return x.StartGameEvent
	}
	return nil
}

type isBroadcastEvent_Event interface {
	isBroadcastEvent_Event()
}

type BroadcastEvent_ReadyEvent struct {
	ReadyEvent *ReadyEvent `protobuf:"bytes,2,opt,name=readyEvent,proto3,oneof"`
}

type BroadcastEvent_StartGameEvent struct {
	StartGameEvent *StartGameEvent `protobuf:"bytes,3,opt,name=startGameEvent,proto3,oneof"`
}

func (*BroadcastEvent_ReadyEvent) isBroadcastEvent_Event() {}

func (*BroadcastEvent_StartGameEvent) isBroadcastEvent_Event() {}

//准备事件
type ReadyEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string  `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Ready  bool    `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"` //true准备，false取消准备
	Player *Player `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *ReadyEvent) Reset() {
	*x = ReadyEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyEvent) ProtoMessage() {}

func (x *ReadyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyEvent.ProtoReflect.Descriptor instead.
func (*ReadyEvent) Descriptor() ([]byte, []int) {
	return file_broadcast_event_proto_rawDescGZIP(), []int{1}
}

func (x *ReadyEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ReadyEvent) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadyEvent) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

//开始游戏事件
type StartGameEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` //展示没有什么用
}

func (x *StartGameEvent) Reset() {
	*x = StartGameEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameEvent) ProtoMessage() {}

func (x *StartGameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameEvent.ProtoReflect.Descriptor instead.
func (*StartGameEvent) Descriptor() ([]byte, []int) {
	return file_broadcast_event_proto_rawDescGZIP(), []int{2}
}

func (x *StartGameEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_broadcast_event_proto protoreflect.FileDescriptor

var file_broadcast_event_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x5f, 0x62,
	0x72, 0x69, 0x63, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x1a, 0x0c, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc3, 0x01, 0x0a, 0x0e, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x41, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x79, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x62, 0x72, 0x65, 0x61,
	0x6b, 0x5f, 0x62, 0x72, 0x69, 0x63, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x65,
	0x61, 0x64, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x4d, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x5f, 0x62, 0x72, 0x69, 0x63, 0x6b, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0x6f, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x33, 0x0a, 0x06,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62,
	0x72, 0x65, 0x61, 0x6b, 0x5f, 0x62, 0x72, 0x69, 0x63, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x22, 0x24, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x67, 0x61, 0x6d, 0x65, 0x66,
	0x69, 0x73, 0x68, 0x2f, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x42, 0x72, 0x69, 0x63, 0x6b, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_broadcast_event_proto_rawDescOnce sync.Once
	file_broadcast_event_proto_rawDescData = file_broadcast_event_proto_rawDesc
)

func file_broadcast_event_proto_rawDescGZIP() []byte {
	file_broadcast_event_proto_rawDescOnce.Do(func() {
		file_broadcast_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_broadcast_event_proto_rawDescData)
	})
	return file_broadcast_event_proto_rawDescData
}

var file_broadcast_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_broadcast_event_proto_goTypes = []interface{}{
	(*BroadcastEvent)(nil), // 0: break_bricks.protoc.BroadcastEvent
	(*ReadyEvent)(nil),     // 1: break_bricks.protoc.ReadyEvent
	(*StartGameEvent)(nil), // 2: break_bricks.protoc.StartGameEvent
	(*Player)(nil),         // 3: break_bricks.protoc.Player
}
var file_broadcast_event_proto_depIdxs = []int32{
	1, // 0: break_bricks.protoc.BroadcastEvent.readyEvent:type_name -> break_bricks.protoc.ReadyEvent
	2, // 1: break_bricks.protoc.BroadcastEvent.startGameEvent:type_name -> break_bricks.protoc.StartGameEvent
	3, // 2: break_bricks.protoc.ReadyEvent.player:type_name -> break_bricks.protoc.Player
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_broadcast_event_proto_init() }
func file_broadcast_event_proto_init() {
	if File_broadcast_event_proto != nil {
		return
	}
	file_player_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_broadcast_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broadcast_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadyEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broadcast_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGameEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_broadcast_event_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*BroadcastEvent_ReadyEvent)(nil),
		(*BroadcastEvent_StartGameEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_broadcast_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_broadcast_event_proto_goTypes,
		DependencyIndexes: file_broadcast_event_proto_depIdxs,
		MessageInfos:      file_broadcast_event_proto_msgTypes,
	}.Build()
	File_broadcast_event_proto = out.File
	file_broadcast_event_proto_rawDesc = nil
	file_broadcast_event_proto_goTypes = nil
	file_broadcast_event_proto_depIdxs = nil
}
